import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient() as any;

export const platformOwnerFeatures = [
  // Users Management
  {
    name: 'View Users',
    slug: 'users.view',
    description: 'View platform owner users',
    type: 'PLATFORM_OWNER' as const,
    category: 'users',
    isPageLevel: true,
    defaultActions: ['view'],
  },
  {
    name: 'Create Users',
    slug: 'users.create',
    description: 'Create new platform owner users',
    type: 'PLATFORM_OWNER' as const,
    category: 'users',
    isPageLevel: false,
    defaultActions: ['create'],
  },
  {
    name: 'Edit Users',
    slug: 'users.edit',
    description: 'Edit platform owner users',
    type: 'PLATFORM_OWNER' as const,
    category: 'users',
    isPageLevel: false,
    defaultActions: ['edit'],
  },
  {
    name: 'Delete Users',
    slug: 'users.delete',
    description: 'Delete platform owner users',
    type: 'PLATFORM_OWNER' as const,
    category: 'users',
    isPageLevel: false,
    defaultActions: ['delete'],
  },
  // Merchants Management
  {
    name: 'View Merchants',
    slug: 'merchants.view',
    description: 'View all merchants',
    type: 'PLATFORM_OWNER' as const,
    category: 'merchants',
    isPageLevel: true,
    defaultActions: ['view'],
  },
  {
    name: 'Approve Merchants',
    slug: 'merchants.approve',
    description: 'Approve merchant registrations',
    type: 'PLATFORM_OWNER' as const,
    category: 'merchants',
    isPageLevel: false,
    defaultActions: ['approve'],
  },
  {
    name: 'Edit Merchants',
    slug: 'merchants.edit',
    description: 'Edit merchant information',
    type: 'PLATFORM_OWNER' as const,
    category: 'merchants',
    isPageLevel: false,
    defaultActions: ['edit'],
  },
  {
    name: 'Delete Merchants',
    slug: 'merchants.delete',
    description: 'Delete merchants',
    type: 'PLATFORM_OWNER' as const,
    category: 'merchants',
    isPageLevel: false,
    defaultActions: ['delete'],
  },
  // Subscriptions Management
  {
    name: 'View Subscriptions',
    slug: 'subscriptions.view',
    description: 'View all subscriptions',
    type: 'PLATFORM_OWNER' as const,
    category: 'subscriptions',
    isPageLevel: true,
    defaultActions: ['view'],
  },
  {
    name: 'Manage Subscriptions',
    slug: 'subscriptions.manage',
    description: 'Extend, reset, and reactivate subscriptions',
    type: 'PLATFORM_OWNER' as const,
    category: 'subscriptions',
    isPageLevel: false,
    defaultActions: ['extend', 'reset', 'reactivate'],
  },
  // Analytics
  {
    name: 'View Platform Analytics',
    slug: 'analytics.view',
    description: 'View platform-wide analytics',
    type: 'PLATFORM_OWNER' as const,
    category: 'analytics',
    isPageLevel: true,
    defaultActions: ['view'],
  },
  // Settings
  {
    name: 'View Settings',
    slug: 'settings.view',
    description: 'View platform settings',
    type: 'PLATFORM_OWNER' as const,
    category: 'settings',
    isPageLevel: true,
    defaultActions: ['view'],
  },
  {
    name: 'Edit Settings',
    slug: 'settings.edit',
    description: 'Edit platform settings',
    type: 'PLATFORM_OWNER' as const,
    category: 'settings',
    isPageLevel: false,
    defaultActions: ['edit'],
  },
  // Roles Management
  {
    name: 'View Roles',
    slug: 'roles.view',
    description: 'View all roles',
    type: 'PLATFORM_OWNER' as const,
    category: 'roles',
    isPageLevel: true,
    defaultActions: ['view'],
  },
  {
    name: 'Create Roles',
    slug: 'roles.create',
    description: 'Create new roles',
    type: 'PLATFORM_OWNER' as const,
    category: 'roles',
    isPageLevel: false,
    defaultActions: ['create'],
  },
  {
    name: 'Edit Roles',
    slug: 'roles.edit',
    description: 'Edit existing roles',
    type: 'PLATFORM_OWNER' as const,
    category: 'roles',
    isPageLevel: false,
    defaultActions: ['edit'],
  },
  {
    name: 'Delete Roles',
    slug: 'roles.delete',
    description: 'Delete roles',
    type: 'PLATFORM_OWNER' as const,
    category: 'roles',
    isPageLevel: false,
    defaultActions: ['delete'],
  },
  // Features Management
  {
    name: 'View Features',
    slug: 'features.view',
    description: 'View all system features',
    type: 'PLATFORM_OWNER' as const,
    category: 'features',
    isPageLevel: true,
    defaultActions: ['view'],
  },
  {
    name: 'Create Features',
    slug: 'features.create',
    description: 'Create new features',
    type: 'PLATFORM_OWNER' as const,
    category: 'features',
    isPageLevel: false,
    defaultActions: ['create'],
  },
  {
    name: 'Edit Features',
    slug: 'features.edit',
    description: 'Edit existing features',
    type: 'PLATFORM_OWNER' as const,
    category: 'features',
    isPageLevel: false,
    defaultActions: ['edit'],
  },
];

export const merchantFeatures = [
  // Products Management
  {
    name: 'View Products',
    slug: 'products.view',
    description: 'View products',
    type: 'MERCHANT' as const,
    category: 'products',
    isPageLevel: true,
    defaultActions: ['view'],
  },
  {
    name: 'Create Products',
    slug: 'products.create',
    description: 'Create new products',
    type: 'MERCHANT' as const,
    category: 'products',
    isPageLevel: false,
    defaultActions: ['create'],
  },
  {
    name: 'Edit Products',
    slug: 'products.edit',
    description: 'Edit existing products',
    type: 'MERCHANT' as const,
    category: 'products',
    isPageLevel: false,
    defaultActions: ['edit'],
  },
  {
    name: 'Delete Products',
    slug: 'products.delete',
    description: 'Delete products',
    type: 'MERCHANT' as const,
    category: 'products',
    isPageLevel: false,
    defaultActions: ['delete'],
  },
  // Sales Management
  {
    name: 'View Sales',
    slug: 'sales.view',
    description: 'View sales records',
    type: 'MERCHANT' as const,
    category: 'sales',
    isPageLevel: true,
    defaultActions: ['view'],
  },
  {
    name: 'Create Sales',
    slug: 'sales.create',
    description: 'Create new sales',
    type: 'MERCHANT' as const,
    category: 'sales',
    isPageLevel: false,
    defaultActions: ['create'],
  },
  {
    name: 'Edit Sales',
    slug: 'sales.edit',
    description: 'Edit existing sales',
    type: 'MERCHANT' as const,
    category: 'sales',
    isPageLevel: false,
    defaultActions: ['edit'],
  },
  {
    name: 'Delete Sales',
    slug: 'sales.delete',
    description: 'Delete sales',
    type: 'MERCHANT' as const,
    category: 'sales',
    isPageLevel: false,
    defaultActions: ['delete'],
  },
  // Inventory Management
  {
    name: 'View Inventory',
    slug: 'inventory.view',
    description: 'View inventory',
    type: 'MERCHANT' as const,
    category: 'inventory',
    isPageLevel: true,
    defaultActions: ['view'],
  },
  {
    name: 'Manage Inventory',
    slug: 'inventory.manage',
    description: 'Adjust inventory stock',
    type: 'MERCHANT' as const,
    category: 'inventory',
    isPageLevel: false,
    defaultActions: ['adjust', 'restock'],
  },
  // Analytics
  {
    name: 'View Analytics',
    slug: 'analytics.view',
    description: 'View merchant analytics',
    type: 'MERCHANT' as const,
    category: 'analytics',
    isPageLevel: true,
    defaultActions: ['view'],
  },
  // Users Management (Merchant)
  {
    name: 'View Users',
    slug: 'users.view',
    description: 'View merchant users',
    type: 'MERCHANT' as const,
    category: 'users',
    isPageLevel: true,
    defaultActions: ['view'],
  },
  {
    name: 'Create Users',
    slug: 'users.create',
    description: 'Create new merchant users',
    type: 'MERCHANT' as const,
    category: 'users',
    isPageLevel: false,
    defaultActions: ['create'],
  },
  {
    name: 'Edit Users',
    slug: 'users.edit',
    description: 'Edit merchant users',
    type: 'MERCHANT' as const,
    category: 'users',
    isPageLevel: false,
    defaultActions: ['edit'],
  },
  {
    name: 'Delete Users',
    slug: 'users.delete',
    description: 'Delete merchant users',
    type: 'MERCHANT' as const,
    category: 'users',
    isPageLevel: false,
    defaultActions: ['delete'],
  },
  // Settings
  {
    name: 'View Settings',
    slug: 'settings.view',
    description: 'View merchant settings',
    type: 'MERCHANT' as const,
    category: 'settings',
    isPageLevel: true,
    defaultActions: ['view'],
  },
  {
    name: 'Edit Settings',
    slug: 'settings.edit',
    description: 'Edit merchant settings',
    type: 'MERCHANT' as const,
    category: 'settings',
    isPageLevel: false,
    defaultActions: ['edit'],
  },
];

export async function seedFeatures() {
  console.log('Seeding features...');

  const allFeatures = [...platformOwnerFeatures, ...merchantFeatures];

  for (const feature of allFeatures) {
    await prisma.feature.upsert({
      where: { slug: feature.slug },
      update: {
        name: feature.name,
        description: feature.description,
        type: feature.type,
        category: feature.category,
        isPageLevel: feature.isPageLevel,
        defaultActions: feature.defaultActions,
      },
      create: {
        name: feature.name,
        slug: feature.slug,
        description: feature.description,
        type: feature.type,
        category: feature.category,
        isPageLevel: feature.isPageLevel,
        defaultActions: feature.defaultActions,
      },
    });
  }

  console.log(`Seeded ${allFeatures.length} features`);
}

