-- AlterEnum: Add new transaction types
ALTER TYPE "InventoryTransactionType" ADD VALUE 'TRANSFER_IN';
ALTER TYPE "InventoryTransactionType" ADD VALUE 'TRANSFER_OUT';
ALTER TYPE "InventoryTransactionType" ADD VALUE 'STOCK_IN';

-- CreateTable: Locations
CREATE TABLE "locations" (
    "id" TEXT NOT NULL,
    "merchantId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT,
    "phone" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "locations_pkey" PRIMARY KEY ("id")
);

-- CreateTable: Inventory (immutable stock entries)
CREATE TABLE "inventory" (
    "id" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "locationId" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "batchNumber" TEXT,
    "expirationDate" TIMESTAMP(3),
    "receivedDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "notes" TEXT,
    "addedBy" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "inventory_pkey" PRIMARY KEY ("id")
);

-- CreateIndex: Locations
CREATE UNIQUE INDEX "locations_merchantId_name_key" ON "locations"("merchantId", "name");
CREATE INDEX "locations_merchantId_idx" ON "locations"("merchantId");

-- CreateIndex: Inventory
CREATE INDEX "inventory_productId_idx" ON "inventory"("productId");
CREATE INDEX "inventory_locationId_idx" ON "inventory"("locationId");
CREATE INDEX "inventory_batchNumber_idx" ON "inventory"("batchNumber");
CREATE INDEX "inventory_expirationDate_idx" ON "inventory"("expirationDate");

-- AddForeignKey: Locations
ALTER TABLE "locations" ADD CONSTRAINT "locations_merchantId_fkey" FOREIGN KEY ("merchantId") REFERENCES "merchants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey: Inventory
ALTER TABLE "inventory" ADD CONSTRAINT "inventory_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "inventory" ADD CONSTRAINT "inventory_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "inventory" ADD CONSTRAINT "inventory_addedBy_fkey" FOREIGN KEY ("addedBy") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Data Migration: Create default locations for existing merchants
-- Note: IDs will be generated by Prisma's cuid() when using ORM
-- For migration, we'll use a simple approach - create locations with temporary IDs
-- The application will handle proper ID generation
DO $$
DECLARE
    merchant_record RECORD;
    location_id TEXT;
BEGIN
    FOR merchant_record IN SELECT "id" FROM "merchants" WHERE NOT EXISTS (
        SELECT 1 FROM "locations" WHERE "merchantId" = "merchants"."id"
    )
    LOOP
        -- Generate a simple ID (in production, Prisma will use cuid)
        location_id := 'loc_' || substr(md5(random()::text || merchant_record."id"), 1, 21);
        INSERT INTO "locations" ("id", "merchantId", "name", "isActive", "isDefault", "createdAt", "updatedAt")
        VALUES (
            location_id,
            merchant_record."id",
            'Main Warehouse',
            true,
            true,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        );
    END LOOP;
END $$;

-- AlterTable: Add locationId, referenceId, referenceType to inventory_transactions
ALTER TABLE "inventory_transactions" ADD COLUMN "locationId" TEXT;
ALTER TABLE "inventory_transactions" ADD COLUMN "referenceId" TEXT;
ALTER TABLE "inventory_transactions" ADD COLUMN "referenceType" TEXT;

-- Data Migration: Set locationId for existing transactions (use default location)
UPDATE "inventory_transactions" it
SET "locationId" = (
    SELECT l."id" 
    FROM "locations" l 
    WHERE l."merchantId" = it."merchantId" 
    AND l."isDefault" = true 
    LIMIT 1
)
WHERE "locationId" IS NULL;

-- Make locationId required
ALTER TABLE "inventory_transactions" ALTER COLUMN "locationId" SET NOT NULL;

-- CreateIndex: Inventory transactions
CREATE INDEX "inventory_transactions_locationId_idx" ON "inventory_transactions"("locationId");
CREATE INDEX "inventory_transactions_productId_locationId_idx" ON "inventory_transactions"("productId", "locationId");

-- AddForeignKey: Inventory transactions location
ALTER TABLE "inventory_transactions" ADD CONSTRAINT "inventory_transactions_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Data Migration: Migrate existing stockQuantity to Inventory entries
DO $$
DECLARE
    product_record RECORD;
    location_record RECORD;
    user_record RECORD;
    inventory_id TEXT;
BEGIN
    FOR product_record IN 
        SELECT p."id", p."merchantId", p."stockQuantity", p."createdAt"
        FROM "products" p
        WHERE p."stockQuantity" > 0
    LOOP
        -- Get default location for this merchant
        SELECT * INTO location_record
        FROM "locations"
        WHERE "merchantId" = product_record."merchantId" AND "isDefault" = true
        LIMIT 1;

        -- Get a user for this merchant (prefer admin, otherwise any user)
        SELECT * INTO user_record
        FROM "users"
        WHERE "merchantId" = product_record."merchantId"
        ORDER BY CASE WHEN "role" = 'MERCHANT_ADMIN' THEN 1 ELSE 2 END
        LIMIT 1;

        -- Only create inventory entry if location and user exist
        IF location_record IS NOT NULL AND user_record IS NOT NULL THEN
            inventory_id := 'inv_' || substr(md5(random()::text || product_record."id" || location_record."id"), 1, 21);
            INSERT INTO "inventory" ("id", "productId", "locationId", "quantity", "receivedDate", "addedBy", "createdAt")
            VALUES (
                inventory_id,
                product_record."id",
                location_record."id",
                product_record."stockQuantity",
                COALESCE(product_record."createdAt", CURRENT_TIMESTAMP),
                user_record."id",
                CURRENT_TIMESTAMP
            );
        END IF;
    END LOOP;
END $$;

-- Data Migration: Create STOCK_IN transactions for migrated inventory entries
-- Create transactions for all inventory entries that reference the migration
DO $$
DECLARE
    inventory_record RECORD;
    product_record RECORD;
    transaction_id TEXT;
BEGIN
    FOR inventory_record IN 
        SELECT i.* FROM "inventory" i
        WHERE NOT EXISTS (
            SELECT 1 FROM "inventory_transactions" t 
            WHERE t."referenceId" = i."id" AND t."referenceType" = 'STOCK_MIGRATION'
        )
    LOOP
        SELECT * INTO product_record FROM "products" WHERE "id" = inventory_record."productId";
        
        IF product_record IS NOT NULL THEN
            transaction_id := 'txn_' || substr(md5(random()::text || inventory_record."id" || CURRENT_TIMESTAMP::text), 1, 21);
            INSERT INTO "inventory_transactions" ("id", "merchantId", "productId", "locationId", "userId", "type", "quantity", "referenceId", "referenceType", "reason", "createdAt")
            VALUES (
                transaction_id,
                product_record."merchantId",
                inventory_record."productId",
                inventory_record."locationId",
                inventory_record."addedBy",
                'STOCK_IN',
                inventory_record."quantity",
                inventory_record."id",
                'STOCK_MIGRATION',
                'Migrated from product.stockQuantity',
                inventory_record."createdAt"
            );
        END IF;
    END LOOP;
END $$;

-- AlterTable: Remove previousStock and newStock from inventory_transactions
ALTER TABLE "inventory_transactions" DROP COLUMN "previousStock";
ALTER TABLE "inventory_transactions" DROP COLUMN "newStock";

-- AlterTable: Remove stockQuantity from products
ALTER TABLE "products" DROP COLUMN "stockQuantity";

